### ISSUE TITLE
lacks guile support in the latest 8011 build

### ISSUE THREAD

**Issue by inter1965** [bernhardcl/coot#6]
also curlew is missing

**Comment by bernhardcl** [comment]
These are related. I decided (a long time ago) not to bother with guile builds (on Windows) any more since the graphics module (guile-gtk) is not working on Windows (and very old and very deprecated). Most functions are available under python so why worry!? Curlew is different in several ways but I hope to have this integrated at some point (pythonic though).

**Comment by inter1965** [comment]
Since there're still a lot of extensions from curlew (.e.g. curlew-black-box-morph-and-fit.scm, curlew-chain-refine.scm, curlew-click-click-refine-residues.scm,  curlew-expand-map-radius.scm, curlew-morph-march.scm, curlew-pepflip-complicado.scm, curlew-stroke-characters.scm) are using scheme.

**Comment by bernhardcl** [comment]
Curlew has been included in WinCoot now and missing functions ported to python. The future of Coot is python....
