### ISSUE TITLE
I am using

### ISSUE THREAD

**Issue by alburse** [bernhardcl/coot#9]

**Comment by alburse** [comment]
I am trying to use wincoot0.9beta2. However, when I try to do real space refinement, I get this error
Warning: Refinement setup failure. Failed to find restraint for: ALA PHE ....

I can run the real space refinement with the same map and model using CCP4 coot on ubuntu.

Would you please let me know if I am missing something? 

Thank you

Alpay

When I examined the command line I saw these warnings

(coot-bin.exe:19508): GLib-GObject-WARNING **: 17:08:04.267: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'
WARNING:: The reference structures directory (COOT_REF_STRUCTS): C:\WinCoot\bin\\..\share\coot\reference-structures was not found.
          Ca->Mainchain will not be possible.
WARNING:: Coot REFMAC dictionary override COOT_REFMAC_LIB_DIRfailed to find a dictionary C:\WinCoot\bin\\..\share\coot\lib
WARNING:: COOT_PREFIX set, but no dictionary lib found
WARNING: Failed to read restraints dictionary.
WARNING: in init_refmac_mon_lib, file "/data/monomers/list/mon_lib_list.cif" not found.
WARNING: file /data/monomers/a/ALA.cif is not a regular file
WARNING: file /data/monomers/a/ASP.cif is not a regular file
..
..
WARNING:: energy lib /data/monomers/ener_lib.cif not found.

**Comment by bernhardcl** [comment]
This is because it is currently shipped without a dictionary, so you will need to provide this yourself. Sorry about this. Here is how you can fix it:

- Copy the dictionary from elsewhere (e.g. Phenix, https://www2.mrc-lmb.cam.ac.uk/groups/murshudov/content/refmac/Dictionary/dictionary.html) to be in yourwincootdir/share/coot/lib

- either in Windows (set environment variable) or the wincoot64.bat file edit
 o CLIBD_MON is defined to point to the dictionary directory (e.g. phenix or old coot)
 o define COOT_REFMAC_LIB_DIR to point to a dictionary directory

Hope to pack the next one with a dictionary to avoid any issues...

B

**Comment by alburse** [comment]
Thank you Bernhard. 

Just to clarify, we need to place the "monomer" directory under WinCoot/share/coot/lib/data
and set the COOT_REFMAC_LIB as "set COOT_REFMAC_LIB_DIR=%COOT_SHARE%\coot\lib"

I did not understand the CLIBD_MON part and did not set it. Still, real space refinement is working now. 

Alpay
